name: Deployment

on: [push]

#on:
#  workflow_dispatch:
#  push:
#    branches:
#      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install dependencies
      run: |
        echo test
    - name: Run the deployment script
      run: echo ${{secrets.ABC}}
